

###
POST http://localhost:8080/rest/api/person/
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"fname": "Kirzten", "lname": "DerAldrigErPå", "phone": 1234}

###
GET http://localhost:8080/rest/api/person/id/8
Content-Type: application/json



###
DELETE http://localhost:8080/rest/api/person/delete/8
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

###

GET http://localhost:8080/rest/api/person/all
Content-Type: application/json

###

PUT http://localhost:8080/rest/api/person/update/9
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{
  "fname": "Lucas",
  "lname": "DerAldrigErPå",
  "phone": "12345"
}


###

