GET http://localhost:8080/devops_starter_war_exploded/api/xxx

###
POST http://localhost:8080/dat3_startcode_war_exploded/api/person/
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "Kristian Hartmann", "age": 25}

###
PUT http://localhost:8080/dat3_startcode_war_exploded/api/person/2
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "Kristian", "age": 15}

###
GET http://localhost:8080/dat3_startcode_war_exploded/api/person/user/6
